apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: new-go-test
  janus-idp.io/tekton: new-go-test
  backstage.io/kubernetes-id: new-go-test
  backstage.io/kubernetes-namespace: target-ns 
  app.kubernetes.io/part-of: new-go-test
resources: 
- deployment.yaml
- route.yaml
- service.yaml
